channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.3
- pip:
  - mlflow==2.10.0
  - cloudpickle==3.0.0
  - numpy==1.26.3
  - packaging==23.1
  - pyyaml==6.0.1
  - scikit-learn==1.4.0
  - scipy==1.12.0
name: mlflow-env
